development:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: ssm_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: ssm_test
  pool: 5

production:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: ssm_production
  pool: 5
  username: <%= ENV['KCSC_DB_USER'] %>
  password: <%= ENV['KCSC_DB_PASSWORD'] %>
